# Generated by Django 5.0.1 on 2026-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
