# Generated by Django 5.0.1 on 2026-02-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='community_icons/')),
                ('introduction', models.TextField(blank=True)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('events_per_year', models.PositiveIntegerField(default=0)),
                ('cultural_objects', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='communities.community')),
            ],
        ),
    ]
