# Generated by Django 6.0.2 on 2026-03-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_announcement_delete_faq_delete_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('focus', models.CharField(blank=True, max_length=255)),
                ('badge', models.CharField(blank=True, help_text='Short label shown on the image (e.g. Founder, Programs)', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
