# Generated by Django 5.0.1 on 2026-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('partnership_since', models.DateField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
