# Generated by Django 5.0.1 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('volunteer_type', models.CharField(choices=[('general', 'General Volunteer'), ('expertise', 'Expertise-based Volunteer')], default='general', max_length=20)),
                ('expertise', models.CharField(blank=True, help_text='Relevant skill area for expertise volunteers', max_length=200)),
                ('schedule_availability', models.CharField(help_text='When you are available to volunteer', max_length=250)),
                ('purpose', models.TextField(help_text='Why do you want to volunteer?')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]