# Generated by Django 6.0.2 on 2026-03-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
    ]
