# Generated by Django 6.0.2 on 2026-03-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_volunteerapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrequest',
            name='assigned_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='volunteers.volunteeropportunity'),
        ),
        migrations.AlterField(
            model_name='volunteerrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('closed', 'Rejected')], default='new', max_length=20),
        ),
    ]
