# Generated by Django 6.0.2 on 2026-05-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_volunteerrequest_assigned_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary image shown on the volunteer detail page and for social sharing', null=True, upload_to='volunteer_images/'),
        ),
    ]
