# Generated by Django 5.0.1 on 2026-03-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='donation',
            name='interact_email',
            field=models.EmailField(blank=True, help_text='Email for Interact e-Transfer', max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('interact', 'Interact e-Transfer')], default='interact', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
