# Generated by Django 5.0.1 on 2026-03-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_donor_email_donation_donor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('interact', 'Interact e-Transfer'), ('card', 'Credit/Debit Card')], default='interact', max_length=20),
        ),
    ]
