# Generated by Django 5.0.1 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_card_last_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
