# Generated by Django 6.0.2 on 2026-03-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
