# Generated by Django 5.0.1 on 2026-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('is_virtual', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('cultural', 'Cultural'), ('workshop', 'Workshop'), ('meeting', 'Meeting'), ('festival', 'Festival'), ('other', 'Other')], default='other', max_length=50)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('registered_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
