# Generated by Django 5.0.1 on 2026-03-03 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('programs', '0004_requestevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestevent',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='requestevent',
            name='handled',
        ),
        migrations.AddField(
            model_name='requestevent',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communities.community'),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='created_program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_event', to='programs.program'),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='event_type',
            field=models.CharField(choices=[('festival', 'Festival'), ('workshop', 'Workshop'), ('meeting', 'Meeting'), ('cultural', 'Cultural'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
