# Generated by Django 6.0.2 on 2026-03-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_alter_requestevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='live_stream_url',
            field=models.URLField(blank=True),
        ),
    ]
