# Generated by Django 6.0.2 on 2026-05-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_live_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='ticket_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
