# Generated by Django 6.0.2 on 2026-05-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_program_start_time_program_ticket_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='program',
            name='ticket_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tickets'),
        ),
    ]
