# Generated by Django 6.0.2 on 2026-05-25 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_add_program_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, help_text='Optional maximum attendees for the event', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_closed',
            field=models.BooleanField(default=False, help_text='Admin can manually close registrations'),
        ),
        migrations.AddField(
            model_name='program',
            name='waitlist_enabled',
            field=models.BooleanField(default=False, help_text='Allow users to join a waitlist when the event is full'),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='programs.program')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'program'), name='unique_waitlist_user_program'), models.UniqueConstraint(condition=models.Q(('guest_email', ''), _negated=True), fields=('guest_email', 'program'), name='unique_waitlist_guest_email_program')],
            },
        ),
    ]
